// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dErDvWPnyKvMfD5m4jpnKM
// Component: ib1ew39akEPg
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: emxQNjUI4uHX/component
import Button from "../../Button"; // plasmic-import: 9mok55OwiDz/component
import Price from "../../Price"; // plasmic-import: QMZVs1ClYf9q/component
import Select from "../../Select"; // plasmic-import: pdS8OvCxNCRU/component
import Select__Option from "../../Select__Option"; // plasmic-import: Z_VPSIz8jnw8/component
import Separator from "../../Separator"; // plasmic-import: CZauEleNtWdG/component
import ProductCard from "../../ProductCard"; // plasmic-import: GbmcqALz6wB/component
import Rating from "../../Rating"; // plasmic-import: z75gCb4cZKTa/component
import Footer from "../../Footer"; // plasmic-import: dP2xEJNU1vI_/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: FTRLMKer0YEQ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: dErDvWPnyKvMfD5m4jpnKM/projectcss
import * as sty from "./PlasmicItem.module.css"; // plasmic-import: ib1ew39akEPg/css

import HomeIcon from "./icons/PlasmicIcon__Home"; // plasmic-import: xyPyd99u4YK8/icon
import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: OxBpFUQdtlgI/icon
import LikeIcon from "./icons/PlasmicIcon__Like"; // plasmic-import: 9AzX_ubb0lPN/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: ps7eTn4tBj9r/icon

export type PlasmicItem__VariantMembers = {};

export type PlasmicItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicItem__VariantsArgs;
export const PlasmicItem__VariantProps = new Array<VariantPropType>();

export type PlasmicItem__ArgsType = {
  container42?: React.ReactNode;
};

type ArgPropType = keyof PlasmicItem__ArgsType;
export const PlasmicItem__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicItem__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  container432?: p.Flex<"div">;
  price?: p.Flex<typeof Price>;
  quantity?: p.Flex<typeof Select>;
  likeButton?: p.Flex<typeof Button>;
  addToCartButton?: p.Flex<typeof Button>;
  description?: p.Flex<"div">;
  details?: p.Flex<"div">;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultItemProps {
  dataFetches: PlasmicItem__Fetches;
}

function PlasmicItem__RenderFunc(props: {
  variants: PlasmicItem__VariantsArgs;
  args: PlasmicItem__ArgsType;
  overrides: PlasmicItem__OverridesType;
  dataFetches?: PlasmicItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Item"}</title>
        <meta key="og:title" property="og:title" content={"Item"} />
        <meta
          key="description"
          property="og:description"
          name="description"
          content={
            "Nunc parturient ultricies condimentum parturient sagittis urna mus conubia himenaeos fermentum leo mus dignissim pulvinar blandit porta eget ad."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section__zcj39)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container432"}
              data-plasmic-override={overrides.container432}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container432)}
            >
              <Button
                startIcon={
                  <HomeIcon
                    className={classNames(defaultcss.all, sty.svg__t9MR)}
                    role={"img"}
                  />
                }
              >
                {"Mens"}
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__szxp2
                )}
              >
                {"/"}
              </div>

              <Button
                startIcon={
                  <HomeIcon
                    className={classNames(defaultcss.all, sty.svg__sYbq2)}
                    role={"img"}
                  />
                }
              >
                {"Shoes"}
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__nYtqI
                )}
              >
                {"/"}
              </div>

              <Button
                startIcon={
                  <HomeIcon
                    className={classNames(defaultcss.all, sty.svg__fXEk)}
                    role={"img"}
                  />
                }
              >
                {"Running"}
              </Button>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__wb3Sf)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__stzLf)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___5Fpus)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__aNooj)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: "/plasmic/ecommerce_starter/images/shoe20.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__mEhCl)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__bHw0P)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__d5O0)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/ecommerce_starter/images/shoe28.png",
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__vfsfU)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fjSy)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/ecommerce_starter/images/shoe23.png",
                        fullWidth: 450,
                        fullHeight: 450,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__ha37Y)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__as3Rn)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__iTjSr)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/ecommerce_starter/images/shoe26.png",
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__dNhLb)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___4HNmm)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/ecommerce_starter/images/shoe27.png",
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__oMGq2)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__bUa96)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xyAvz)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/ecommerce_starter/images/shoe24.png",
                        fullWidth: 2000,
                        fullHeight: 2000,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__qzT2)}
                  >
                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jm7En)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: "/plasmic/ecommerce_starter/images/shoe25.png",
                          fullWidth: 2000,
                          fullHeight: 2000,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}
                  </div>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__e1H5P)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__bvgZs
                  )}
                >
                  {"Eternity NITRO Men's Running Shoes"}
                </div>

                <Price
                  data-plasmic-name={"price"}
                  data-plasmic-override={overrides.price}
                  className={classNames("__wab_instance", sty.price)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__ig0Le)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__x5Eqy)}
                    displayHeight={"64px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"64px" as const}
                    src={{
                      src: "/plasmic/ecommerce_starter/images/shoe21.png",
                      fullWidth: 450,
                      fullHeight: 450,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nlqyz)}
                    displayHeight={"64px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"64px" as const}
                    src={{
                      src: "/plasmic/ecommerce_starter/images/shoe22.png",
                      fullWidth: 450,
                      fullHeight: 450,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___02SEi)}
                    displayHeight={"64px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"64px" as const}
                    src={{
                      src: "/plasmic/ecommerce_starter/images/shoe23.png",
                      fullWidth: 450,
                      fullHeight: 450,
                      aspectRatio: undefined
                    }}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__vp198)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__its32
                    )}
                  >
                    {"Size"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__yjbdz)}
                  >
                    <Button colors={"lightGrayOutline" as const}>{"7"}</Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__euExI
                        )}
                      >
                        {"7.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__cuLjy
                        )}
                      >
                        {"8"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__qbYUd
                        )}
                      >
                        {"8.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___2Hib6
                        )}
                      >
                        {"9"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__wTz1R
                        )}
                      >
                        {"9.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___100GZ
                        )}
                      >
                        {"10"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__oMana
                        )}
                      >
                        {"10.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___9Byy9
                        )}
                      >
                        {"11"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__e71Wo
                        )}
                      >
                        {"11.5"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__qLyup
                        )}
                      >
                        {"12"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___3LTdf
                        )}
                      >
                        {"13"}
                      </div>
                    </Button>

                    <Button colors={"lightGrayOutline" as const}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__twzzi
                        )}
                      >
                        {"14"}
                      </div>
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__t0Aqm)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__dzrUt)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__gmKqo
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <Select
                      data-plasmic-name={"quantity"}
                      data-plasmic-override={overrides.quantity}
                      className={classNames("__wab_instance", sty.quantity)}
                      defaultValue={"1" as const}
                    >
                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option___1VIgt
                        )}
                        value={"1" as const}
                      >
                        {"1"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__pni6M
                        )}
                        value={"2" as const}
                      >
                        {"2"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__fJzj0
                        )}
                        value={"3" as const}
                      >
                        {"3"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__dfv32
                        )}
                        value={"4" as const}
                      >
                        {"4"}
                      </Select__Option>

                      <Select__Option
                        className={classNames(
                          "__wab_instance",
                          sty.option___50W3X
                        )}
                        value={"5" as const}
                      >
                        {"5"}
                      </Select__Option>
                    </Select>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__zuxXc)}
                  >
                    <Button
                      data-plasmic-name={"likeButton"}
                      data-plasmic-override={overrides.likeButton}
                      colors={"lightGrayOutline" as const}
                      iconOnly={"iconOnly" as const}
                      size={"large" as const}
                      startIcon={
                        <LikeIcon
                          className={classNames(defaultcss.all, sty.svg__d005X)}
                          role={"img"}
                        />
                      }
                    />

                    <Button
                      data-plasmic-name={"addToCartButton"}
                      data-plasmic-override={overrides.addToCartButton}
                      colors={"black" as const}
                      link={"/cart" as const}
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Add to cart"}
                    </Button>
                  </p.Stack>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__g7B8Q)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__kbZl)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__pj10B
                    )}
                  >
                    {"Description"}
                  </div>

                  <div
                    data-plasmic-name={"description"}
                    data-plasmic-override={overrides.description}
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.description
                    )}
                  >
                    {
                      "Let Eternity NITRO be your guide. The engineered mesh upper integrates the runGUIDE tech, designed to hug your midfoot for an effortless ride. For the midsole, NITRO foam provides superior cushioning, combining with other tech elements to give you support: a TPU heel piece for proprioception, reflectivity, and a durable rubber PUMAGRIP for all-surface traction. You lead the way, Eternity NITRO will keep you in line."
                    }
                  </div>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__nCfgi)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__dmiA)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__jeNl5
                    )}
                  >
                    {"Details"}
                  </div>

                  <div
                    data-plasmic-name={"details"}
                    data-plasmic-override={overrides.details}
                    className={classNames(defaultcss.all, sty.details)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___3XjXi
                      )}
                    >
                      {"Adaptive fit with midfoot wrap for secure lockdown"}
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator___92Hrh
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__rHiHk
                      )}
                    >
                      {"Engineered mesh upper for support"}
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator___21Vqj
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__q1T5H
                      )}
                    >
                      {"Full lace closure for snug fit"}
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator__gkhE
                      )}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__vgrcz
                      )}
                    >
                      {
                        "NITRO FOAM midsole for lightweight, responsive cushioning"
                      }
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__v3Wpe)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__zp8Zm)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__fdIk2
                      )}
                    >
                      {"You may also like"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__bbHzb
                      )}
                      colors={"link" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__n7Uk4)}
                          role={"img"}
                        />
                      }
                      showEndIcon={"showEndIcon" as const}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__bS3G)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"http://google.com" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___1PcD6
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__l75Gb
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iAifs
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uOSy
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__famen
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__je1VP
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ixKsk
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__qfrl0
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vR1S1
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__zprL
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__okF2
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__odNkM
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lpBXw
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__mQzQ
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__d3ThC
                  )}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container432",
    "price",
    "quantity",
    "likeButton",
    "addToCartButton",
    "description",
    "details",
    "container42",
    "container5",
    "footer"
  ],
  navBar: ["navBar"],
  container432: ["container432"],
  price: ["price"],
  quantity: ["quantity"],
  likeButton: ["likeButton"],
  addToCartButton: ["addToCartButton"],
  description: ["description"],
  details: ["details"],
  container42: ["container42"],
  container5: ["container5"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container432: "div";
  price: typeof Price;
  quantity: typeof Select;
  likeButton: typeof Button;
  addToCartButton: typeof Button;
  description: "div";
  details: "div";
  container42: "div";
  container5: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicItem__VariantsArgs;
    args?: PlasmicItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicItem__Fetches;
  } & Omit<PlasmicItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicItem__ArgProps,
      internalVariantPropNames: PlasmicItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItem";
  } else {
    func.displayName = `PlasmicItem.${nodeName}`;
  }
  return func;
}

export const PlasmicItem = Object.assign(
  // Top-level PlasmicItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container432: makeNodeComponent("container432"),
    price: makeNodeComponent("price"),
    quantity: makeNodeComponent("quantity"),
    likeButton: makeNodeComponent("likeButton"),
    addToCartButton: makeNodeComponent("addToCartButton"),
    description: makeNodeComponent("description"),
    details: makeNodeComponent("details"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicItem
    internalVariantProps: PlasmicItem__VariantProps,
    internalArgProps: PlasmicItem__ArgProps
  }
);

export default PlasmicItem;
/* prettier-ignore-end */
