// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dErDvWPnyKvMfD5m4jpnKM
// Component: j1wakR_PtqzS
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: emxQNjUI4uHX/component
import Button from "../../Button"; // plasmic-import: 9mok55OwiDz/component
import ProductCard from "../../ProductCard"; // plasmic-import: GbmcqALz6wB/component
import Rating from "../../Rating"; // plasmic-import: z75gCb4cZKTa/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: 03VSjVcdHWxO/component
import Value from "../../Value"; // plasmic-import: PJxO9P8cvog/component
import Footer from "../../Footer"; // plasmic-import: dP2xEJNU1vI_/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: FTRLMKer0YEQ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: dErDvWPnyKvMfD5m4jpnKM/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: j1wakR_PtqzS/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: OxBpFUQdtlgI/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: ps7eTn4tBj9r/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: 3GbaBKeXSUMQ/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: bNYoGXg5OGUz/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: s1vhHT8lNgiK/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: BVDjg4LGCJE0/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: x13KyIh9UjOV/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: YyEiuYFv5Kzp/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: YUT6NTkYHtsO/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: XPykwV_A9Xmt/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  container42?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  img?: p.Flex<typeof p.PlasmicImg>;
  container3?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  container4?: p.Flex<"div">;
  container?: p.Flex<"div">;
  emojiValueProps?: p.Flex<typeof EmojiValueProps>;
  columns?: p.Flex<"div">;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  container6?: p.Flex<"div">;
  container434?: p.Flex<"div">;
  container433?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomepageProps {
  dataFetches: PlasmicHomepage__Fetches;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"ShoeShop"}</title>
        <meta key="og:title" property="og:title" content={"ShoeShop"} />
        <meta
          key="description"
          property="og:description"
          name="description"
          content={
            "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section__s2ZS3)}>
            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"none" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              src={{
                src: "/plasmic/ecommerce_starter/images/hero.png",
                fullWidth: 2048,
                fullHeight: 1415,
                aspectRatio: undefined
              }}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__oEvha)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__rswSd)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      defaultcss.h1,
                      defaultcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Norma Collection"}
                  </h1>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hUNk
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </p.Stack>

                <Button
                  className={classNames("__wab_instance", sty.button__mL2ZM)}
                  colors={"black" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(defaultcss.all, sty.svg__fcrdk)}
                      role={"img"}
                    />
                  }
                  link={"/category" as const}
                  rounded={"rounded" as const}
                  showEndIcon={"showEndIcon" as const}
                  size={"large" as const}
                >
                  {"Shop"}
                </Button>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__syFcu)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(defaultcss.all, sty.container4)}
            >
              <div className={classNames(defaultcss.all, sty.freeBox__iGk87)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__vNxCu
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__izps2)}
                  colors={"link" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(defaultcss.all, sty.svg__ex7Ot)}
                      role={"img"}
                    />
                  }
                  link={"/category" as const}
                  showEndIcon={"showEndIcon" as const}
                >
                  {"See more"}
                </Button>
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__oegr2)}
                img={{
                  src: "/plasmic/ecommerce_starter/images/shoe14.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                link={"/item" as const}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__fl8Ar)}
                    rating={"four" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__bxsfx
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___7Cc5I
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__hm7Yu)}
                dollars={"79"}
                img={{
                  src: "/plasmic/ecommerce_starter/images/shoe15.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                link={"/item" as const}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___921Nv)}
                    rating={"threeHalf" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___1ZoXm
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__k92HV
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__u7B2W)}
                dollars={"64"}
                img={{
                  src: "/plasmic/ecommerce_starter/images/shoe16.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                link={"/item" as const}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__qJtOc)}
                    rating={"two" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__mr62I
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___2SEiR
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___0Dubm
                )}
                dollars={"99"}
                img={{
                  src: "/plasmic/ecommerce_starter/images/shoe17.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                link={"/item" as const}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__tklHq)}
                    rating={"four" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__qGJr
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___7XNfp
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___9XEIy
                )}
                dollars={"79"}
                img={{
                  src: "/plasmic/ecommerce_starter/images/shoe18.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                link={"/item" as const}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__kpbFv)}
                    rating={"five" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__uNqSz
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__keRt3
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard__sMxkN)}
                dollars={"65"}
                img={{
                  src: "/plasmic/ecommerce_starter/images/shoe19.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                link={"/item" as const}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__mqDFr)}
                    rating={"threeHalf" as const}
                  />
                }
                tags={
                  <Button colors={"lightGray" as const} size={"small" as const}>
                    {"New"}
                  </Button>
                }
              />
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__dnnkE)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__hMo9J)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__exYsT)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___4XJgs)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__o7Ryi
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__iqc33
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__gCjRw)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__qfUq0
                    )}
                  >
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                    >
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </span>
                  </div>

                  <Button
                    colors={"black" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(defaultcss.all, sty.svg__roWIw)}
                        role={"img"}
                      />
                    }
                    link={"/category" as const}
                    rounded={"rounded" as const}
                    showEndIcon={"showEndIcon" as const}
                    size={"large" as const}
                  >
                    {"Shop sale"}
                  </Button>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(defaultcss.all, sty.columns)}
            >
              <div className={classNames(defaultcss.all, sty.column___4RjYb)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__cElfz
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__z3EAl)}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___08Qk1)}
                  icon={
                    <PlaneIcon
                      className={classNames(defaultcss.all, sty.svg__dxmQ)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ly05D
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___2NJgO
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>

              <div className={classNames(defaultcss.all, sty.column__ufl8B)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__fcLc7
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___6UUd1
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__fncU)}
                  icon={
                    <DocumentIcon
                      className={classNames(defaultcss.all, sty.svg__kyIw5)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__sw0B9
                    )}
                  >
                    {"30-day guarantee"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___9XmVc
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>

              <div className={classNames(defaultcss.all, sty.column__a2Mt7)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vNsty
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__h2S5H)}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__p5ZkG)}
                  icon={
                    <LockIcon
                      className={classNames(defaultcss.all, sty.svg__wfg8N)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0TbgC
                    )}
                  >
                    {"Secured payments"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__fF2Uy
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </p.Stack>
          </EmojiValueProps>

          <section className={classNames(defaultcss.all, sty.section__jg7Vk)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__nqH1G)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__l8Tsy
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__s0SFh
                      )}
                      colors={"link" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__mYbur)}
                          role={"img"}
                        />
                      }
                      link={"/category" as const}
                      showEndIcon={"showEndIcon" as const}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__ztTbu)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uaaDx
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rDrE
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ckOi
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0HbXv
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__s8Faz
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__l4ObT
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ypgxD
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__x6H37
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__whJ9Y
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hfnd5
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__x6JBc
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__k2S2J
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__nrVc
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___30AU5
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__uHh9K
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe19.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <section className={classNames(defaultcss.all, sty.section__hemqO)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__exLCn)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__bKKs1
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__gz3Ec)}
                  states={"active" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hfaV1
                    )}
                  >
                    {"All"}
                  </div>
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__o4TF1)}
                >
                  {"New"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__k37Dg)}
                >
                  {"Womens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__yab4D)}
                >
                  {"Mens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__p4Ew0)}
                >
                  {"Kids"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__faq87)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__wiNbS
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__qggLx)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fD1H0
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rZf2T
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__tStny
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___1Gpsy
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__npjhu
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lQu3R
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nk43V
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uRa7
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bMxEk
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jmr8
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__auvoG
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__e7OlT
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iaVfV
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__gTi0Z
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___8D0Gp
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__doW5K
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__dYctk
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__spCk8
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__kLghd
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___8Mb2
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__qfIUo
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__o9MvL
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__yqNf3
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__maTs
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__sxx5Y
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__u7SFc
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__jAdWp
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames("__wab_instance", sty.productCard__jQ0)}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bN85
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lmbO8
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gzmny
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__nsArk
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vmlVq
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__trUc7
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lApsi
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__mii6O
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__quWTo)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container434)}
            >
              <Value
                center={"center" as const}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__srk8B)}
                    colors={"black" as const}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(defaultcss.all, sty.svg___1Viwc)}
                        role={"img"}
                      />
                    }
                    rounded={"rounded" as const}
                    showEndIcon={"showEndIcon" as const}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value__cwe5)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(defaultcss.all, sty.svg__o3OhP)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom" as const}
                withButton={"withButton" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__gPx62
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___14R2W
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__jewkP)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container433)}
            >
              <div className={classNames(defaultcss.all, sty.column__s9Ue7)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__m2VB6
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg___1Axo)}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___9YmOi)}
                  icon={
                    <MedalIcon
                      className={classNames(defaultcss.all, sty.svg___2ZGmr)}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__cNrzK
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__sY5By
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__untnP)}
                    colors={"link" as const}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>

              <div className={classNames(defaultcss.all, sty.column__xd8Gn)}>
                <Value
                  children2={
                    <Button
                      className={classNames("__wab_instance", sty.button__kC8S)}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__awtGa)}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__cG4Sj)}
                  icon={
                    <LeafIcon
                      className={classNames(defaultcss.all, sty.svg__vem17)}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__dn299
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__y3Az9
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__hRWuL)}
                    colors={"link" as const}
                  />
                </Value>
              </div>

              <div className={classNames(defaultcss.all, sty.column__vgGwS)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__qnLtq
                      )}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__uXSb4)}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__juepV)}
                  icon={
                    <ShoeIcon
                      className={classNames(defaultcss.all, sty.svg__vvvz)}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__urVv3
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__rw9Uv
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__uxCkg)}
                    colors={"link" as const}
                  />
                </Value>
              </div>

              <div className={classNames(defaultcss.all, sty.column__yjDac)}>
                <Value
                  children2={
                    <Button
                      className={classNames("__wab_instance", sty.button__vdrN)}
                      colors={"black" as const}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(defaultcss.all, sty.svg__jxoOa)}
                          role={"img"}
                        />
                      }
                      rounded={"rounded" as const}
                      size={"large" as const}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__xixMc)}
                  icon={
                    <PeaceIcon
                      className={classNames(defaultcss.all, sty.svg__jTbU8)}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__izt9N
                    )}
                  >
                    {"We give back for every sale."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___9AOo4
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__rjbGh)}
                    colors={"link" as const}
                  />
                </Value>
              </div>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "img",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],
  navBar: ["navBar"],
  img: ["img"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  img: typeof p.PlasmicImg;
  container3: "div";
  h1: "h1";
  container4: "div";
  container: "div";
  emojiValueProps: typeof EmojiValueProps;
  columns: "div";
  container42: "div";
  container5: "div";
  container6: "div";
  container434: "div";
  container433: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    img: makeNodeComponent("img"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
