// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dErDvWPnyKvMfD5m4jpnKM
// Component: Vl_kn_zzhfTJ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: emxQNjUI4uHX/component
import Button from "../../Button"; // plasmic-import: 9mok55OwiDz/component
import ProductCard from "../../ProductCard"; // plasmic-import: GbmcqALz6wB/component
import Rating from "../../Rating"; // plasmic-import: z75gCb4cZKTa/component
import Footer from "../../Footer"; // plasmic-import: dP2xEJNU1vI_/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: FTRLMKer0YEQ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: dErDvWPnyKvMfD5m4jpnKM/projectcss
import * as sty from "./PlasmicCategory.module.css"; // plasmic-import: Vl_kn_zzhfTJ/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: OxBpFUQdtlgI/icon
import FilledCircleIcon from "./icons/PlasmicIcon__FilledCircle"; // plasmic-import: FxMH_h2WCBad/icon
import EmptyCircleIcon from "./icons/PlasmicIcon__EmptyCircle"; // plasmic-import: TwCqCcCBal06/icon

export type PlasmicCategory__VariantMembers = {};

export type PlasmicCategory__VariantsArgs = {};
type VariantPropType = keyof PlasmicCategory__VariantsArgs;
export const PlasmicCategory__VariantProps = new Array<VariantPropType>();

export type PlasmicCategory__ArgsType = {};
type ArgPropType = keyof PlasmicCategory__ArgsType;
export const PlasmicCategory__ArgProps = new Array<ArgPropType>();

export type PlasmicCategory__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  section?: p.Flex<"section">;
  container6?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultCategoryProps {
  dataFetches: PlasmicCategory__Fetches;
}

function PlasmicCategory__RenderFunc(props: {
  variants: PlasmicCategory__VariantsArgs;
  args: PlasmicCategory__ArgsType;
  overrides: PlasmicCategory__OverridesType;
  dataFetches?: PlasmicCategory__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Category"}</title>
        <meta key="og:title" property="og:title" content={"Category"} />
        <meta
          key="description"
          property="og:description"
          name="description"
          content={
            "Inceptos tempor torquent tortor a aptent parturient a a himenaeos in ipsum ad vestibulum euismod ultrices dis vulputate vestibulum non adipiscing."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen" as const}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(defaultcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__tkK3J)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__ve0E)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uhtHi
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__wq0Gp)}
                    states={"active" as const}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__t6LH
                      )}
                    >
                      {"All"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__tq1O7)}
                  >
                    {"New"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__a73CS)}
                  >
                    {"Womens"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__og2Lm)}
                  >
                    {"Mens"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__hgqdH)}
                  >
                    {"Kids"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__tJcP)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___0WNi
                      )}
                    >
                      {"On sale"}
                    </div>
                  </Button>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__piiCa)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__b10Aa
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__l9Qcy)}
                  >
                    {"$0 - $50"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__cQJ0)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text___6Xch2
                      )}
                    >
                      {"$51 - $99"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__anZ4A)}
                  >
                    {"$101+"}
                  </Button>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___3Snnu)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vtH8O
                    )}
                  >
                    {"Colors"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__iU1V)}
                  >
                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___4GlOl
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__ujCwb
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___1Z6Sh
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__oCvI
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__iGwHj)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__jPrEf
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__viAZs)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__k2Hre
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__cgkDy)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___0Ckn7
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__anurU)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__olNvX
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__yKszn)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___3FZ2V
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__ntJIw)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__diRuk
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__d29L)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__b9Njh
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__qjE4C)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__bN47S
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__u3YhA)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__jZ4Iz
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__uZTtr)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__yex2K
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg__hrMpH)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__i7Fxm
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(defaultcss.all, sty.svg___3Zzk)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text___4Dnky
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <EmptyCircleIcon
                          className={classNames(defaultcss.all, sty.svg__dQmaz)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text__mZm06
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___65Ns)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___9Uy6
                    )}
                  >
                    {"Brands"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__soXXr)}
                  >
                    {"Adidas"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__zBlja)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text__wvgvB
                      )}
                    >
                      {"Asics"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__t9Bq)}
                  >
                    {"Crocs"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__wx94M)}
                  >
                    {"Fila"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__nrbV2)}
                  >
                    {"Nike"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__aKbt7)}
                  >
                    {"Puma"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__aogfP)}
                  >
                    {"Reebok"}
                  </Button>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__anA78)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jiYrV
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__tadiM
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hNfy
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tzFbg
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vw3R
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__muC3W
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___9G3CV
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___20Q8V
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__eoxj7
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nrxYz
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hy9T
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ieJc1
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yF4Od
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xx5GO
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___1Sqs
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xoGok
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__if2U
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bgQVj
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0Dhqk
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__kzUaz
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__dUqag
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__k2Tt8
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__uiTs5
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vts6N
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__j6EFr
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__khcFo
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__g2XHr
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bLXcs
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__xZnd7
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__r0Y14
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___4WNs7
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__gcZaz
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__ggTob
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___2VTi
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__mVkXy
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0YQOq
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__sNjEm
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__cVcco
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__pcyMr
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ag5Rc
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__hNfBk
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___2Sl4S
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___6Mw7J
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__r7Jci
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__lam9
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tjvcs
                  )}
                  img={{
                    src: "/plasmic/ecommerce_starter/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___0StNo
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bbYt7
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  section: "section";
  container6: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCategory__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCategory__VariantsArgs;
    args?: PlasmicCategory__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCategory__Fetches;
  } & Omit<PlasmicCategory__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCategory__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCategory__ArgProps,
      internalVariantPropNames: PlasmicCategory__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCategory__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCategory";
  } else {
    func.displayName = `PlasmicCategory.${nodeName}`;
  }
  return func;
}

export const PlasmicCategory = Object.assign(
  // Top-level PlasmicCategory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCategory
    internalVariantProps: PlasmicCategory__VariantProps,
    internalArgProps: PlasmicCategory__ArgProps
  }
);

export default PlasmicCategory;
/* prettier-ignore-end */
