// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dErDvWPnyKvMfD5m4jpnKM
// Component: z75gCb4cZKTa
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: dErDvWPnyKvMfD5m4jpnKM/projectcss
import * as sty from "./PlasmicRating.module.css"; // plasmic-import: z75gCb4cZKTa/css

import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: D15p1XzMT_GR/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: 28POkMxiqpaI/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: 7nvW-xt9w4e3/icon

export type PlasmicRating__VariantMembers = {
  rating:
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf";
};

export type PlasmicRating__VariantsArgs = {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
};

type VariantPropType = keyof PlasmicRating__VariantsArgs;
export const PlasmicRating__VariantProps = new Array<VariantPropType>("rating");

export type PlasmicRating__ArgsType = {};
type ArgPropType = keyof PlasmicRating__ArgsType;
export const PlasmicRating__ArgProps = new Array<ArgPropType>();

export type PlasmicRating__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRatingProps {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
  className?: string;
}

function PlasmicRating__RenderFunc(props: {
  variants: PlasmicRating__VariantsArgs;
  args: PlasmicRating__ArgsType;
  overrides: PlasmicRating__OverridesType;
  dataFetches?: PlasmicRating__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(defaultcss.all, sty.svg__vs07K, {
          [sty.svg__rating_five__vs07KSnNq1]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__vs07KJ5JiC]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__vs07KU2MI]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_half__vs07KFcswI]: hasVariant(
            variants,
            "rating",
            "half"
          ),
          [sty.svg__rating_oneHalf__vs07KSzHgt]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svg__rating_one__vs07KxLo9K]: hasVariant(
            variants,
            "rating",
            "one"
          ),
          [sty.svg__rating_threeHalf__vs07KDRhYx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svg__rating_three__vs07KeFjBm]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svg__rating_twoHalf__vs07KJ0Hk]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svg__rating_two__vs07KxsCuk]: hasVariant(
            variants,
            "rating",
            "two"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(defaultcss.all, sty.svg__zVaao, {
          [sty.svg__rating_five__zVaaoSnNq1]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__zVaaoJ5JiC]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__zVaaoU2MI]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_oneHalf__zVaaoSzHgt]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svg__rating_threeHalf__zVaaoDRhYx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svg__rating_three__zVaaoeFjBm]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svg__rating_twoHalf__zVaaoJ0Hk]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svg__rating_two__zVaaoxsCuk]: hasVariant(
            variants,
            "rating",
            "two"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(defaultcss.all, sty.svg__uKMkk, {
          [sty.svg__rating_five__uKMkkSnNq1]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__uKMkkJ5JiC]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__uKMkkU2MI]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_threeHalf__uKMkkDRhYx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svg__rating_three__uKMkkeFjBm]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svg__rating_twoHalf__uKMkkJ0Hk]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(defaultcss.all, sty.svg__nAyGp, {
          [sty.svg__rating_five__nAyGpSnNq1]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__nAyGpj5JiC]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__nAyGpU2MI]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_threeHalf__nAyGpdRhYx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(defaultcss.all, sty.svg___5BMhY, {
          [sty.svg__rating_five___5BMhYSnNq1]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf___5BMhYj5JiC]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRating__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRating__VariantsArgs;
    args?: PlasmicRating__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRating__Fetches;
  } & Omit<PlasmicRating__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRating__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
